### ISSUE TITLE
Exception if I try to use localizationsDelegates

### ISSUE THREAD

**Issue by joaowd** [MMMzq/bot_toast#11]
I'm trying to use this package but I'm having the following error:

```
flutter: ══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
flutter: The following assertion was thrown during a scheduler callback:
flutter:          Initialization error.
flutter:          The initialization method has been modified in version 2.0.
flutter:          do you wrapped you app widget like this?
flutter:
flutter:          BotToastInit(
flutter:                child: MaterialApp(
flutter:                  navigatorObservers: [BotToastNavigatorObserver()],
flutter:                  home: EnterPage(),
flutter:                ),
flutter:              );
flutter: 'package:bot_toast/src/toast.dart':
flutter: Failed assertion: line 83 pos 14: 'null'
flutter:
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:
flutter:   https://github.com/flutter/flutter/issues/new?template=BUG.md
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #2      BotToast.init.<anonymous closure> 
package:bot_toast/src/toast.dart:83
flutter: #3      _safeRun.<anonymous closure> 
package:bot_toast/src/toast.dart:14
flutter: #4      SchedulerBinding._invokeFrameCallback 
package:flutter/…/scheduler/binding.dart:1033
flutter: #5      SchedulerBinding.handleDrawFrame 
package:flutter/…/scheduler/binding.dart:983
flutter: #6      SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> 
package:flutter/…/scheduler/binding.dart:784
flutter: #15     _Timer._runTimers  (dart:isolate-patch/timer_impl.dart:382:19)
flutter: #16     _Timer._handleMessage  (dart:isolate-patch/timer_impl.dart:416:5)
flutter: #17     _RawReceivePortImpl._handleMessage  (dart:isolate-patch/isolate_patch.dart:172:12)
```

My code:

```
      return BotToastInit(
        child: MaterialApp(
          navigatorObservers: [BotToastNavigatorObserver()],
          title: getTitle(),
          theme: getTheme(),
          initialRoute: getInitialRoute(),
          onGenerateRoute: getRoutes,
          supportedLocales: getLocalization().supportedLocales(),
          localizationsDelegates: <LocalizationsDelegate<dynamic>>[
            l10nService,
            GlobalMaterialLocalizations.delegate, 
            GlobalWidgetsLocalizations.delegate,
            GlobalCupertinoLocalizations.delegate,
          ]);

```

If I dont use "localizationsDelegates" the library works fine:

```
     return BotToastInit(
        child: MaterialApp(
          navigatorObservers: [BotToastNavigatorObserver()],
          title: getTitle(),
          theme: getTheme(),
          initialRoute: getInitialRoute(),
          onGenerateRoute: getRoutes));
```

**Comment by joaowd** [comment]
Btw I love your library! Really well done!

**Comment by MMMzq** [comment]
Thank you very much, I am trying to reproduce the problem.

**Comment by joaowd** [comment]
Any luck ?

**Comment by MMMzq** [comment]
If it still doesn't work, you can provide an example to me, I will do my best to help.

**Comment by joaowd** [comment]
I think the problem is because in the l10nService I have a async call:

`final String data = await rootBundle.loadString('$_root$lang.json');`

Probably your widget is not waiting for it

**Comment by MMMzq** [comment]
try change:
https://github.com/MMMzq/bot_toast/blob/faaa66119d81b4c7905ae12747a585f9b3d7e783/lib/src/toast.dart#L69-L76

to:
```dart
 if (element.widget is Navigator) { 
    _navigatorState = (element as StatefulElement).state; 
     _init(); 
 }
```

does bot_toast work properly?

**Comment by joaowd** [comment]
Get this error now:

```
flutter: When the exception was thrown, this was the stack:
flutter: #2      BotToast.init.<anonymous closure> 
package:bot_toast/src/toast.dart:79
flutter: #3      _safeRun.<anonymous closure> 
package:bot_toast/src/toast.dart:14
flutter: #4      SchedulerBinding._invokeFrameCallback 
package:flutter/…/scheduler/binding.dart:1033
flutter: #5      SchedulerBinding.handleDrawFrame 
package:flutter/…/scheduler/binding.dart:983
flutter: #6      SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> 
package:flutter/…/scheduler/binding.dart:784
flutter: #15     _Timer._runTimers  (dart:isolate-patch/timer_impl.dart:382:19)
flutter: #16     _Timer._handleMessage  (dart:isolate-patch/timer_impl.dart:416:5)
flutter: #17     _RawReceivePortImpl._handleMessage  (dart:isolate-patch/isolate_patch.dart:172:12)
flutter: (elided 10 frames from class _AssertionError, package dart:async, and package dart:async-patch)
```

> does bot_toast work properly?

If I don't await for the json to load is works.

**Comment by MMMzq** [comment]
Can you provide the code for l10nService?

**Comment by joaowd** [comment]
https://gist.github.com/joaowd/1dd60cfe54c5a700fb5085c69ae497fa

**Comment by joaowd** [comment]
If you are trying to implement this class and you are having difficulties please let me know

**Comment by MMMzq** [comment]
I am using l10nService in the example.
example works fine.
https://gist.github.com/MMMzq/bc030602ebac7ddd021e68cdf4f4188e

**Comment by joaowd** [comment]
Exactly because your are not awaiting to load json.

If you had this:

```
Future<bool> loadLocalizedValues(String root) async {
    final String data = **await** rootBundle.loadString('$root${locale.languageCode}.json');
   ...
}
```

And await for the method here:

```
 @override
  Future<Location> load(Locale locale) async {
    _location = Location(locale);
    **await** _location.loadLocalizedValues(_root);
    return _location;
  }
```

It will crash

**Comment by MMMzq** [comment]
I successfully reproduced this problem.
Thanks.

**Comment by MMMzq** [comment]
I will inform you if I have any progress. 😊

**Comment by joaowd** [comment]
Any news?

**Comment by MMMzq** [comment]
> Any news? Have you found out why it happens ?

I already know the reason, I am trying to solve it.

**Comment by MMMzq** [comment]
I have solved this problem, but I still need time to check. Make sure there are no problems

**Comment by MMMzq** [comment]
@joaowd 
Upgrade `2.1.0` version fix bug

**Comment by joaowd** [comment]
@MMMzq Just tested it it works!

Thank you.
