### ISSUE TITLE
how i can handle it in background.

### ISSUE THREAD

**Issue by jayeshindianic** [MMMzq/bot_toast#118]
i used this plugin to show push notification, its working if app is in foreground but if app is in backgroung or terminated its throw error when pushnotification is comming.

how i can handle it in background.

```
[ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: 'package:bot_toast/src/bot_toast_init.dart': Failed assertion: line 9 pos 10: '_key.currentState != null': is not true.
E/flutter ( 8434): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
E/flutter ( 8434): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
E/flutter ( 8434): #2      botToastManager (package:bot_toast/src/bot_toast_init.dart:9:10)
E/flutter ( 8434): #3      BotToast.showWidget (package:bot_toast/src/toast.dart:882:5)
E/flutter ( 8434): #4      BotToast.showEnhancedWidget (package:bot_toast/src/toast.dart:822:18)
E/flutter ( 8434): #5      BotToast.showAnimationWidget (package:bot_toast/src/toast.dart:660:12)
E/flutter ( 8434): #6      BotToast.showCustomNotification (package:bot_toast/src/toast.dart:239:12)
E/flutter ( 8434): #7      BotToast.showNotification (package:bot_toast/src/toast.dart:171:12)
```

version
`  bot_toast: ^4.0.1`

 flutter doctor
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.5, on Mac OS X 10.15.7 19H15 darwin-x64, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0-rc1)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.55.2)
[✓] Connected device (3 available)

• No issues found!
```

**Comment by MMMzq** [comment]
This problem may be related to BotToast not being initialized!
