### ISSUE TITLE
弹出框中的Slider控件滑动出错

### ISSUE THREAD

**Issue by anonymity-X** [MMMzq/bot_toast#138]
在AttachedToast中添加Slider控件，当滑动滑块时报错。

### 错误内容：
````======== Exception caught by gesture ===============================================================
The following _CastError was thrown while handling a gesture:
Null check operator used on a null value
When the exception was thrown, this was the stack: 
#0      _SliderState.showValueIndicator (package:flutter/src/material/slider.dart:810:26)
#1      _RenderSlider._startInteraction (package:flutter/src/material/slider.dart:1255:12)
#2      _RenderSlider._handleDragStart (package:flutter/src/material/slider.dart:1297:5)
#3      DragGestureRecognizer._checkStart.<anonymous closure> (package:flutter/src/gestures/monodrag.dart:429:53)
#4      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:198:24)
#5      DragGestureRecognizer._checkStart (package:flutter/src/gestures/monodrag.dart:429:7)
#6      DragGestureRecognizer.acceptGesture (package:flutter/src/gestures/monodrag.dart:349:7)
#7      _CombiningGestureArenaMember.acceptGesture (package:flutter/src/gestures/team.dart:42:14)
#8      GestureArenaManager._resolveByDefault (package:flutter/src/gestures/arena.dart:251:25)
#9      GestureArenaManager._tryToResolveArena.<anonymous closure> (package:flutter/src/gestures/arena.dart:232:31)
(elided 10 frames from dart:async)
Handler: "onStart"
Recognizer: HorizontalDragGestureRecognizer#23459
  start behavior: start
====================================================================================================
````

###  源码：
```` 
class PopupDemo extends StatefulWidget{
  const PopupDemo({Key? key}) : super(key: key);
  @override
  State<PopupDemo> createState() => _PopupDemoState();
}
class _PopupDemoState extends State<PopupDemo>{
  late double _thresholdWidthValue = 50.0;
  late double _thresholdHeightValue = 50.0;
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text("popup demo"),
      ),
    body: Builder(builder: (BuildContext context){
      return ElevatedButton(
        onPressed: (){
          show(context: context);
        },
        child: const Text("点我呀!!!"),
      );
    })
    );
  }
  CancelFunc show({ BuildContext? context, Offset? target}) {
    return BotToast.showAttachedWidget(
        target: target,
        targetContext: context,
        // verticalOffset: verticalOffset, // 垂直偏移,如果实际显示的方向为水平居中则该参数无效
        // horizontalOffset: horizontalOffset,
        preferDirection: PreferDirection.bottomCenter, // 偏好方向,如果在空间允许的情况下,会偏向显示在那边
        onlyOne: true, // 表示是否该分组内是否在同一时间里只存在一个Toast,区分是哪一个组是按照[groupKey]来区分的
        allowClick: false, // 是否在该Toast显示时,能否正常点击触发事件
        enableSafeArea: true, // 如果为true则toast确保不会显示在app状态栏上面(意味着是安全的),false则反之
        // backgroundColor: Colors.blue,
        // clickClose: ture, // 是否在点击屏幕触发事件时自动关闭该Toast
        attachedBuilder: (cancel) => (Card(
          color: Colors.grey,
          child: Container(
            padding: const EdgeInsets.symmetric(horizontal: 8),
            child: Column(
              mainAxisSize: MainAxisSize.min,
              children: <Widget>[
                Text("自定义参数"),
                Row(
                  // crossAxisAlignment: CrossAxisAlignment.center,
                  mainAxisAlignment: MainAxisAlignment.spaceEvenly,
                  children: [
                    const Text("宽度："),
                    Slider(
                        value: _thresholdWidthValue,
                        min: 1,
                        max: 255,
                        divisions: 5,
                        label: '$_thresholdWidthValue', // 滑动过程中在上方显示标签
                        onChanged: (value){
                          print("当前值： $value");
                          setState((){
                            _thresholdWidthValue =  value;
                          });
                        }
                    ),
                  ],
                ),
                Row(
                  // crossAxisAlignment: CrossAxisAlignment.center,
                  mainAxisAlignment: MainAxisAlignment.spaceEvenly,
                  children: [
                    const Text("高度："),
                    Slider(
                        value: _thresholdHeightValue,
                        min: 1,
                        max: 255,
                        divisions: 5,
                        label: '$_thresholdHeightValue', // 滑动过程中在上方显示标签
                        onChanged: (value){
                          print("当前值： $value");
                          setState((){
                            _thresholdHeightValue =  value;
                          });
                        }
                    ),
                  ],
                ),
                Row(
                  mainAxisAlignment: MainAxisAlignment.spaceAround,
                  children: [
                    ElevatedButton(child: Text("取消"), onPressed: (){
                      print("取消 ");
                      cancel();
                    },),
                    ElevatedButton(child: Text("确定"), onPressed: (){
                      print("确定 ");
                      cancel();
                    },)
                  ],
                )
              ],
            ),
          ),
        )));
  }
}
````

###  Version
- Flutter 3.0.0 • channel stable • 
- OS: Android
- bot_toast: 4.0.2

**Comment by MMMzq** [comment]
可以参考以下的解决方法:
1.
```dart
    final builder = BotToastInit();
    return MaterialApp(
      builder: (context, child) {
        child = builder(context, child);
        //1. 使用Overlay
        return Overlay(
          initialEntries: [OverlayEntry(builder: (_) => child)],
        );
      },
      title: 'BotToast Demo',
      navigatorObservers: [BotToastNavigatorObserver()],
      home: EnterPage(),
    );
```
2. 
```dart
        return BotToast.showAttachedWidget(
        ...
        //2.使用StatefulBuilder，并且使用StatefulBuilder传入的setState进行setState
        attachedBuilder: (cancel) => StatefulBuilder(
              builder: (_, setState) {
                return Card(
                  color: Colors.grey,
                  child: Container(
                    padding: const EdgeInsets.symmetric(horizontal: 8),
                    child: Column(
                      mainAxisSize: MainAxisSize.min,
                      children: <Widget>[
                        ....,
                        Row(
                          // crossAxisAlignment: CrossAxisAlignment.center,
                          mainAxisAlignment: MainAxisAlignment.spaceEvenly,
                          children: [
                            const Text("宽度："),
                            Slider(
                                value: _thresholdWidthValue,
                                min: 1,
                                max: 255,
                                divisions: 5,
                                label: '$_thresholdWidthValue',
                                onChanged: (value) {
                                  print("当前值： $value");
                                  setState(() {
                                    _thresholdWidthValue = value;
                                  });
                                }),
                          ],
                        ),
                        ...
                      ],
                    ),
                  ),
                );
              },
            )
```

**Comment by anonymity-X** [comment]
@MMMzq 谢谢
