### ISSUE TITLE
[Error] The getter 'currentState' was called on null.

### ISSUE THREAD

**Issue by wolfgio** [MMMzq/bot_toast#21]
Hi guys! i having the following error every time the app starts

════════ Exception caught by scheduler library ═════════════════════════════════════════════════════
The following NoSuchMethodError was thrown during a scheduler callback:
The getter 'currentState' was called on null.
Receiver: null
Tried calling: currentState

When the exception was thrown, this was the stack: 
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      BotToast.removeAll.<anonymous closure> (package:bot_toast/src/toast.dart:855:21)
#2      _safeRun.<anonymous closure> (package:bot_toast/src/toast.dart:15:13)
#3      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1097:15)
#4      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1044:9)
...

Flutter 1.12.7-pre.7 • channel master • https://github.com/flutter/flutter.git
Framework • revision 0216953674 (2 hours ago) • 2019-11-21 09:41:46 -0800
Engine • revision 7a77e3625d
Tools • Dart 2.7.0
λ MacBook-Pro-de-Ne

**Comment by wolfgio** [comment]
Forget it, i was calling closeAllLoading without previous calling show load
