### ISSUE TITLE
使用报错

### ISSUE THREAD

**Issue by yh4922** [MMMzq/bot_toast#22]
初始化，BotToastInit包在Store.init上也试过了 
```
    return Store.init(
      context: context,
      child: BotToastInit(
        child: MaterialApp(
          title: '海草',
          onGenerateRoute: Application.router.generator, /// 路由主要代码
          debugShowCheckedModeBanner: false, // 去除duBug banner
          home: Builder(
            builder: (context) {
              //-------------------屏幕适配设置
              ScreenUtil.instance = ScreenUtil(width: 750, height: 1334)..init(context);
              //-------------------屏幕适配设置
              return AppPage();
            },
          )
        ),
      )
    );
```

使用
```
  Widget build(BuildContext context) {
    hideStatus();
    return WillPopScope(
      onWillPop: () async {
        BotToast.showText(text:"确定要退出么");  //弹出一个文本框;
        return false;
      }
```

报错信息
```
I/View    (15400): Key down dispatch to io.flutter.view.FlutterView{8e34588 VFE...... .F...... 0,0-1080,1920}, event = KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_BACK, scanCode=158, metaState=0, flags=0x48, repeatCount=0, eventTime=687504485, downTime=687504485, deviceId=19, source=0x101 }
I/ViewRootImpl(15400): finishKeyEvent: handled = true keycode = 4 name=KEYCODE_BACK stage=10: View Post IME stage,inputElapseTime=6 eventTime = 687504485 downTime = 687504485 title= com.example.haicao_app/com.example.haicao_app.MainActivity
I/View    (15400): Key up dispatch to io.flutter.view.FlutterView{8e34588 VFE...... .F...... 0,0-1080,1920}, event = KeyEvent { action=ACTION_UP, keyCode=KEYCODE_BACK, scanCode=158, metaState=0, flags=0x48, repeatCount=0, eventTime=687504598, downTime=687504485, deviceId=19, source=0x101 }
E/flutter (15400): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: 'package:bot_toast/src/toast.dart': Failed assertion: line 57 pos 12: 'null':     Please initialize properly!
E/flutter (15400):     Example:
E/flutter (15400):     BotToastInit(
E/flutter (15400):       child: MaterialApp(
E/flutter (15400):         title: 'BotToast Demo',
E/flutter (15400):         navigatorObservers: [BotToastNavigatorObserver()],
E/flutter (15400):         home: XxxPage()
E/flutter (15400):       ),
E/flutter (15400):     );
E/flutter (15400):
[38;5;244mE/flutter (15400): #0      _AssertionError._doThrowNew  (dart:core-patch/errors_patch.dart:40:39)[39;49m
[38;5;244mE/flutter (15400): #1      _AssertionError._throwNew  (dart:core-patch/errors_patch.dart:36:5)[39;49m
[38;5;248mE/flutter (15400): #2      BotToast._init  (package:bot_toast/src/toast.dart:57:12)[39;49m
[38;5;248mE/flutter (15400): #3      BotToast.showWidget.<anonymous closure>  (package:bot_toast/src/toast.dart:835:9)[39;49m
E/flutter (15400): <asynchronous suspension>
[38;5;248mE/flutter (15400): #4      BotToast.showWidget  (package:bot_toast/src/toast.dart:843:6)[39;49m
[38;5;248mE/flutter (15400): #5      BotToast.showEnhancedWidget  (package:bot_toast/src/toast.dart:771:18)[39;49m
[38;5;248mE/flutter (15400): #6      BotToast.showAnimationWidget  (package:bot_toast/src/toast.dart:648:12)[39;49m
[38;5;248mE/flutter (15400): #7      BotToast.showCustomText  (package:bot_toast/src/toast.dart:392:12)[39;49m
[38;5;248mE/flutter (15400): #8      BotToast.showText  (package:bot_toast/src/toast.dart:344:12)[39;49m
[38;5;248mE/flutter (15400): #9      _GuidPageState.build.<anonymous closure>[39;49m
E/flutter (15400): <asynchronous suspension>
[38;5;244mE/flutter (15400): #10     ModalRoute.willPop[39;49m
E/flutter (15400): <asynchronous suspension>
[38;5;244mE/flutter (15400): #11     NavigatorState.maybePop[39;49m
E/flutter (15400): <asynchronous suspension>
[38;5;244mE/flutter (15400): #12     _WidgetsAppState.didPopRoute[39;49m
E/flutter (15400): <asynchronous suspension>
[38;5;244mE/flutter (15400): #13     WidgetsBinding.handlePopRoute[39;49m
E/flutter (15400): <asynchronous suspension>
[38;5;244mE/flutter (15400): #14     WidgetsBinding._handleNavigationInvocation[39;49m
[38;5;244mE/flutter (15400): #15     MethodChannel._handleAsMethodCall[39;49m
E/flutter (15400): <asynchronous suspension>
[38;5;244mE/flutter (15400): #16     MethodChannel.setMethodCallHandler.<anonymous closure>[39;49m
[38;5;244mE/flutter (15400): #17     _DefaultBinaryMessenger.handlePlatformMessage[39;49m
E/flutter (15400): <asynchronous suspension>
[38;5;244mE/flutter (15400): #18     _invoke3.<anonymous closure>  (dart:ui/hooks.dart:293:15)[39;49m
[38;5;244mE/flutter (15400): #19     _rootRun  (dart:async/zone.dart:1124:13)[39;49m
[38;5;244mE/flutter (15400): #20     _CustomZone.run  (dart:async/zone.dart:1021:19)[39;49m
[38;5;244mE/flutter (15400): #21     _CustomZone.runGuarded  (dart:async/zone.dart:923:7)[39;49m
[38;5;244mE/flutter (15400): #22     _invoke3  (dart:ui/hooks.dart:292:10)[39;49m
[38;5;244mE/flutter (15400): #23     _dispatchPlatformMessage  (dart:ui/hooks.dart:154:5)[39;49m
E/flutter (15400):

[38;5;248m════════ Exception caught by scheduler library ═════════════════════════════════[39;49m
[38;5;244mThe following NoSuchMethodError was thrown during a scheduler callback:[39;49m
The getter 'currentState' was called on null.
Receiver: null
Tried calling: currentState

[38;5;244mWhen the exception was thrown, this was the stack[39;49m
[38;5;244m#0      Object.noSuchMethod  (dart:core-patch/object_patch.dart:51:5)[39;49m
[38;5;248m#1      BotToast.remove.<anonymous closure>  (package:bot_toast/src/toast.dart:849:21)[39;49m
[38;5;248m#2      _safeRun.<anonymous closure>  (package:bot_toast/src/toast.dart:15:13)[39;49m
[38;5;244m#3      SchedulerBinding._invokeFrameCallback[39;49m
[38;5;244m#4      SchedulerBinding.handleDrawFrame[39;49m
[38;5;244m...[39;49m
[38;5;248m════════════════════════════════════════════════════════════════════════════════[39;49m

```

**Comment by MMMzq** [comment]
@yh4922 
请正确初始化!
需要添加`BotToastNavigatorObserver()`
[使用文档](https://github.com/MMMzq/bot_toast#3-initialization-bottoast)

**Comment by yh4922** [comment]
@MMMzq  
可以了 谢谢 没注意看
