### ISSUE TITLE
页面跳转前后toast和showLoading会出现错误

### ISSUE THREAD

**Issue by charmfocus** [MMMzq/bot_toast#43]
退出登录页面：
```dart
BotToast.showText(text:'退出登录成功！');
//封装了fluro路由进行跳转至登录页，并清空栈
NavigatorUtils.push(viewService.context, LoginRouter.loginPage, clearStack: true);
```
登录页面：
```
//...网络判断手机号是否可用
var close = BotToast.showLoading();
//...请求远程接口后回调
close();
```

报如下错误：
```
════════ Exception caught by scheduler library ═════════════════════════════════════════════════════
The following assertion was thrown during a scheduler callback:
The entry used for `below` must be in the Overlay and in the `newEntriesList`.
'package:flutter/src/widgets/overlay.dart':
Failed assertion: line 377 pos 7: 'below == null || (below._overlay == this && _entries.contains(below) && newEntriesList.contains(below))'


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

When the exception was thrown, this was the stack: 
#2      OverlayState.rearrange (package:flutter/src/widgets/overlay.dart:377:7)
#3      BotToastManager._checkNavigatorState.<anonymous closure>.<anonymous closure> (package:bot_toast/src/bot_toast_manager.dart:85:22)
#4      safeRun.<anonymous closure> (package:bot_toast/src/toast.dart:15:13)
#5      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1102:15)
#6      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1049:9)
...
════════════════════════════════════════════════════════════════════════════════════════════════════

```

去掉showText或showLoading其中一个，都正常，就是不能两个一块调用

**Comment by MMMzq** [comment]
请问一下你的flutter 版本是多少？

**Comment by charmfocus** [comment]
> 请问一下你的flutter 版本是多少？

Flutter 1.12.13+hotfix.8 • channel stable

**Comment by charmfocus** [comment]
昨晚定位大概问题是路由跳转时如果clearStack后，
bot_toast_manager中
```dart
    if (_observerProxy == null) {
      _observerProxy = BotToastNavigatorObserverProxy(
        didPush: (route, _) {
          if (route.isFirst) {
            safeRun(() {
              if (_children.isNotEmpty) {
                _navigatorState.overlay
                    .rearrange(_children, below: _children.first);
              }
            });
          }
        },
      );
      BotToastNavigatorObserver.register(_observerProxy);
    }
```
`_children.first`内部的`_overlay`为null，所以才出错的，但这个是个私有属性，无法判断below是否合法。

**Comment by MMMzq** [comment]
这部分逻辑确实有点问题，我又发现了另外的问题

**Comment by MMMzq** [comment]
你好，你这边方便使用下dev分支来测试一下有没有问题吗?
使用方式:
```
dependency_overrides:
  bot_toast:
    git:
      url: https://github.com/MMMzq/bot_toast.git
      ref: dev
```

**Comment by charmfocus** [comment]
> dependency_overrides:
>   bot_toast:
>     git:
>       url: https://github.com/MMMzq/bot_toast.git
>       ref: dev

解决了，感谢！

**Comment by MMMzq** [comment]
`2.3.1`已发布,更新一下就好了
