### ISSUE TITLE
Current State is null !

### ISSUE THREAD

**Issue by nateshmbhat** [MMMzq/bot_toast#63]
```
The following assertion was thrown while handling a gesture:
'package:bot_toast/src/bot_toast_init.dart': Failed assertion: line 10 pos 10: '_key?.currentState != null': is not true.

When the exception was thrown, this was the stack: 
#2      botToastManager (package:bot_toast/src/bot_toast_init.dart:10:10)
#3      BotToast.showWidget (package:bot_toast/src/toast.dart:829:5)
#4      BotToast.showEnhancedWidget (package:bot_toast/src/toast.dart:767:18)
#5      BotToast.showAnimationWidget (package:bot_toast/src/toast.dart:611:12)
#6      BotToast.showCustomText (package:bot_toast/src/toast.dart:331:12)
...
Handler: "onTap"
Recognizer: TapGestureRecognizer#cd9af
  debugOwner: GestureDetector
  state: possible
  won arena
  finalPosition: Offset(241.5, 133.3)
  finalLocalPosition: Offset(91.3, 24.9)
  button: 1
  sent tap down
════════════════════════════════════════════════════════════════════════════════════════════════════
E/flutter (27433): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: NoSuchMethodError: The method 'call' was called on null.
E/flutter (27433): Receiver: null
E/flutter (27433): Tried calling: call()
E/flutter (27433): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
E/flutter (27433): #1      BotToast.showEnhancedWidget.<anonymous closure> (package:bot_toast/src/toast.dart:719:17)
E/flutter (27433): <asynchronous suspension>
E/flutter (27433): #2      BotToast.showEnhancedWidget.<anonymous closure> (package:bot_toast/src/toast.dart)
E/flutter (27433): #3      BotToast.showEnhancedWidget.<anonymous closure> (package:bot_toast/src/toast.dart:738:20)
E/flutter (27433): #4      _rootRun (dart:async/zone.dart:1180:38)
E/flutter (27433): #5      _CustomZone.run (dart:async/zone.dart:1077:19)
E/flutter (27433): #6      _CustomZone.runGuarded (dart:async/zone.dart:979:7)
E/flutter (27433): #7      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
E/flutter (27433): #8      _rootRun (dart:async/zone.dart:1184:13)
E/flutter (27433): #9      _CustomZone.run (dart:async/zone.dart:1077:19)
E/flutter (27433): #10     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1003:23)
E/flutter (27433): #11     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:23:15)
E/flutter (27433): #12     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
E/flutter (27433): #13     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
E/flutter (27433): #14     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
E/flutter (27433): 

```

## Flutter Doctor : 

❯ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 1.18.0-11.1.pre, on Mac OS X 10.15.2 19C57, locale en-GB)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install:
        sudo gem install cocoapods
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.6)
[!] IntelliJ IDEA Community Edition (version 2019.3.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.45.1)
[✓] Connected device (3 available)

! Doctor found issues in 2 categories.

### How I used Bot Toast : 

```
 @override
  Widget build(BuildContext context) {
    return Scaffold(
      body:Column(
              children: [
                RaisedButton(
                  onPressed: () {
                    BotToast.showText(text: 'This is a toast message');
                  },
                  child: Text('Show tooltip'),
                )
              ],
            )
    );
  }
```

**Comment by dromedian** [comment]
how did you fix it? I have the same problem
